# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(476, 231)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushBtn_initSimple = QtWidgets.QPushButton(self.groupBox_2)
        self.pushBtn_initSimple.setObjectName("pushBtn_initSimple")
        self.horizontalLayout_2.addWidget(self.pushBtn_initSimple)
        self.pushBtn_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.pushBtn_clear.setObjectName("pushBtn_clear")
        self.horizontalLayout_2.addWidget(self.pushBtn_clear)
        self.checkBox_editable = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_editable.setObjectName("checkBox_editable")
        self.horizontalLayout_2.addWidget(self.checkBox_editable)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushBtn_initCplex = QtWidgets.QPushButton(self.groupBox_3)
        self.pushBtn_initCplex.setObjectName("pushBtn_initCplex")
        self.verticalLayout_2.addWidget(self.pushBtn_initCplex)
        self.comboBox_withUserData = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_withUserData.setObjectName("comboBox_withUserData")
        self.verticalLayout_2.addWidget(self.comboBox_withUserData)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Selected Content"))
        self.groupBox_2.setTitle(_translate("Form", "Simple ComboBox"))
        self.pushBtn_initSimple.setText(_translate("Form", "Init"))
        self.pushBtn_clear.setText(_translate("Form", "Clear"))
        self.checkBox_editable.setText(_translate("Form", "Editable"))
        self.groupBox_3.setTitle(_translate("Form", "ComboBox with UserData"))
        self.pushBtn_initCplex.setText(_translate("Form", "Init"))
