# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 360)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushBtn_readTime = QtWidgets.QPushButton(self.groupBox)
        self.pushBtn_readTime.setObjectName("pushBtn_readTime")
        self.gridLayout.addWidget(self.pushBtn_readTime, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_time = QtWidgets.QLabel(self.groupBox)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 1, 0, 2, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 1, 1, 2, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.pushBtn_setTime = QtWidgets.QPushButton(self.groupBox)
        self.pushBtn_setTime.setObjectName("pushBtn_setTime")
        self.gridLayout.addWidget(self.pushBtn_setTime, 2, 2, 1, 1)
        self.label_date = QtWidgets.QLabel(self.groupBox)
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 3, 0, 2, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 3, 1, 2, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.pushBtn_setDate = QtWidgets.QPushButton(self.groupBox)
        self.pushBtn_setDate.setObjectName("pushBtn_setDate")
        self.gridLayout.addWidget(self.pushBtn_setDate, 4, 2, 1, 1)
        self.label_datetime = QtWidgets.QLabel(self.groupBox)
        self.label_datetime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_datetime.setObjectName("label_datetime")
        self.gridLayout.addWidget(self.label_datetime, 5, 0, 2, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 5, 1, 2, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 2, 1, 1)
        self.pushBtn_setDTime = QtWidgets.QPushButton(self.groupBox)
        self.pushBtn_setDTime.setObjectName("pushBtn_setDTime")
        self.gridLayout.addWidget(self.pushBtn_setDTime, 6, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_selected = QtWidgets.QLabel(self.groupBox_2)
        self.label_selected.setAlignment(QtCore.Qt.AlignCenter)
        self.label_selected.setObjectName("label_selected")
        self.horizontalLayout_2.addWidget(self.label_selected)
        self.lineEdit_selected = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_selected.setObjectName("lineEdit_selected")
        self.horizontalLayout_2.addWidget(self.lineEdit_selected)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.label_time.setBuddy(self.timeEdit)
        self.label_date.setBuddy(self.dateEdit)
        self.label_datetime.setBuddy(self.dateTimeEdit)
        self.label_selected.setBuddy(self.lineEdit_selected)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Date-Time"))
        self.pushBtn_readTime.setText(_translate("Form", "ReadTime"))
        self.label_4.setText(_translate("Form", "StringShow"))
        self.label_time.setText(_translate("Form", "Time"))
        self.pushBtn_setTime.setText(_translate("Form", "Set"))
        self.label_date.setText(_translate("Form", "Date"))
        self.pushBtn_setDate.setText(_translate("Form", "Set"))
        self.label_datetime.setText(_translate("Form", "Date-Time"))
        self.pushBtn_setDTime.setText(_translate("Form", "Set"))
        self.groupBox_2.setTitle(_translate("Form", "Calender"))
        self.label_selected.setText(_translate("Form", "Selected Date"))
